version: 0.2

env:
  parameter-store:
    SITE_BUCKET: /boilerplate/staticsite/s3/bucket

phases:
  build:
    commands:
      - echo Sync the contents to S3
      - aws s3 sync --acl public-read --exclude index.html --cache-control max-age=31536000 ./build s3://${SITE_BUCKET}/${PASSPORT_PREFIX} --delete
      - echo set the cache-control headers for index.html to prevent browser caching
      - aws s3 cp --acl public-read --cache-control="max-age=60,s-maxage=60" ./build/index.html s3://${SITE_BUCKET}/${PASSPORT_PREFIX}/index.html
